apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: stevenzamg/orchestrator-service
          ports:
            - containerPort: 5004
          volumeMounts:
            - mountPath: "/mnt/data"
              name: ml-volume
      volumes:
        - name: ml-volume
          persistentVolumeClaim:
            claimName: ml-persistent-volume-claim
