apiVersion: v1
kind: Pod
metadata:
  name: orchestrator-pod
spec:
  containers:
    - name: orchestrator
      image: stevenzamg/orchestrator-service
      ports:
        - containerPort: 5004
      envFrom:
        - configMapRef:
            name: microservices-config
      volumeMounts:
        - mountPath: "/mnt/data"
          name: ml-volume
  volumes:
    - name: ml-volume
      persistentVolumeClaim:
        claimName: ml-persistent-volume-claim
