apiVersion: v1
kind: Service
metadata:
  name: recommendations-service
spec:
  selector:
    app: recommendations
  ports:
    - protocol: TCP
      port: 5014
      targetPort: 5014
  type: ClusterIP
