apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
spec:
  selector:
    app: orchestrator
  type: NodePort
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
      nodePort: 30004
