apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
    spec:
      containers:
        - name: data-collector
          image: stevenzamg/data-collector-service
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: "/mnt/data"
              name: ml-volume
      volumes:
        - name: ml-volume
          persistentVolumeClaim:
            claimName: ml-persistent-volume-claim
