apiVersion: v1
kind: Service
metadata:
  name: data-collector-service
spec:
  selector:
    app: data-collector  
  ports:
    - protocol: TCP
      port: 5000        
      targetPort: 5000  
  type: ClusterIP       
